title: NoamZeise
email: enquire@noamzeise.com

description: >- # this means to ignore newlines until "baseurl:"
  A collection of programming projects
baseurl: ""
url: "https://noamzeise.com"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

excerpt_separator: <!-- more -->

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
