title: NoamZeise
email: enquire@noamzeise.com

description: >- # this means to ignore newlines until "baseurl:"
  A collection of programming projects
baseurl: ""

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

excerpt_separator: <!-- more -->